import CallAction from 'components/CallAction'
import Footer from 'components/Footer'
import Header from 'components/Header'
import MainSection from 'components/MainSection'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Manage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Header />
      <main>
        <MainSection />
        <CallAction />
      </main>
      <Footer />
    </>
  )
}
